name: Magic

on:
  watch:
    types: [started]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@004814556e37c54a2f6e31384c9e18e983317366
        with:
          deno-version: v1.x

      - name: Run build script
        run: deno run -A --unstable --allow-env src/mod.ts
        env:
          RP_PACK_UUID: ${{ secrets.RP_PACK_UUID }}
          BP_PACK_UUID: ${{ secrets.BP_PACK_UUID }}
          RP_MODULE_UUID: ${{ secrets.RP_MODULE_UUID }}
          BP_MODULE_UUID: ${{ secrets.BP_MODULE_UUID }}

      - name: Package output
        run: |
          cd ${{ GITHUB.WORKSPACE }}
          mkdir dist
          cd build
          zip -r -0 ../dist/RAINBOW.mcaddon ./rainbow\ *
          zip -r -0 ../dist/docs.zip ./docs
      - name: Upload output
        uses: actions/upload-artifact@v2
        with:
          name: RAINBOW.mcaddon
          path: |
            dist/*.mcaddon
      - name: Upload docs
        uses: actions/upload-artifact@v2
        with:
            name: ðŸŒˆ.zip
            path: |
              dist/docs.zip
